"""Initial migration

Revision ID: cbf925292497
Revises: 
Create Date: 2024-07-09 10:14:41.349947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf925292497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_model_id'), 'example_model', ['id'], unique=False)
    op.create_index(op.f('ix_example_model_name'), 'example_model', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_model_name'), table_name='example_model')
    op.drop_index(op.f('ix_example_model_id'), table_name='example_model')
    op.drop_table('example_model')
    # ### end Alembic commands ###
