name: Evaluate RAG System

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run evaluation
      run: |
        source venv/bin/activate
        python evaluation/evaluate_rag_system.py

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: evaluation-results
        path: evaluation/results.json
